CREATE TABLE Manufacturers(
	[ManufacturerID] INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(30) NOT NULL,
	[EstablishedOn] DATE NOT NULL,
)
CREATE TABLE Models(
	[ModelID] INT PRIMARY KEY IDENTITY(101,1) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[ManufacturerID] INT FOREIGN KEY REFERENCES [Manufacturers]([ManufacturerID]) NOT NULL
)